export const siteConfig = {
  name: "Tolga Bayrak",
  title: "Tolga Bayrak — Full Stack Developer",
  description:
    "Node.js, Express.js, React ve PostgreSQL ekosistemiyle ölçeklenebilir web uygulamaları ve SaaS ürünleri geliştiren Full Stack Developer. Backend mimarisi, API tasarımı ve sistem tasarımı üzerine yazılar.",
  url: "https://bayraktolga.com",
  locale: "tr_TR",
  role: "Full Stack Developer",
  email: "bayraktolga28@gmail.com",
  phone: "+90 537 985 4487",
  phoneHref: "+905379854487",
  social: {
    github: "https://github.com/tolgabayrakdev",
    githubHandle: "tolgabayrakdev",
    linkedin: "https://www.linkedin.com/in/tolgabayrak0/",
  },
  keywords: [
    "Tolga Bayrak",
    "Full Stack Developer",
    "Node.js Developer",
    "React Developer",
    "Express.js",
    "Java Spring Boot",
    "Python FastAPI",
    "Flask",
    "PostgreSQL",
    "Backend Developer",
    "Event-driven mimari",
    "Asenkron sistemler",
    "API tasarımı",
    "Sistem tasarımı",
    "Redis",
    "Clean Code",
    "SOLID",
    "JWT kimlik doğrulama",
    "Web güvenliği",
    "Logging",
    "Monitoring",
    "DevOps",
    "CI/CD",
    "Docker",
    "Coolify",
    "SaaS geliştirici",
    "Yazılım mühendisi",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
